In [5]:
import sympy as sp
import numpy as np

### Null Space

##### nullspace is the set of vectors v for which A.v = 0 or null vector

Usage: to solve systems of linear equations

In [9]:
# find the nullspace of A
A = np.mat([[1,-3,-2],[-5,9,1]])
print("A:", A)

M = sp.Matrix(A)
null_space_A = M.nullspace()

# Print each vector in the null space basis
for vector in null_space_A:
    print(vector)
    
# verify
np.dot(M,M.nullspace())

A: [[ 1 -3 -2]
 [-5  9  1]]
Matrix([[-5/2], [-3/2], [1]])


array([[[0]],

       [[0]]], dtype=object)

In [16]:
# shape of the null space
len(null_space_A), null_space_A[0].shape[0]

(1, 3)

In [25]:
A = sp.Matrix([[1, 2, 3],
            [2, 4, 6]])

In [26]:
null_space_A = A.nullspace()

In [27]:
# shape of the null space
len(null_space_A), null_space_A[0].shape[0]

(2, 3)

In [31]:
# Print each vector in the null space basis
for vector in null_space_A:
    print(vector)

Matrix([[-2], [1], [0]])
Matrix([[-3], [0], [1]])


In [32]:
# verify
np.dot(A,A.nullspace())

array([[[0],
        [0]],

       [[0],
        [0]]], dtype=object)